---

- hosts: all
  gather_facts: false
  tasks:
    - name: Demo directory
      ansible.builtin.file:
        path: /opt/demoansible
        state: directory
        owner: www-data
        group: www-data
        mode: 0775
