---
- name: laestrella integration build
  hosts: localserver
  roles:
    - role: gazellacom-deploy
      gazellacom_mode: build
      gazellacom_project: laestrella                         # client
      gazellacom_environment: integration               #integration, production
      gazellacom_build_profile_customer: laestrella
      gazellacom_build_profile_environment: integration
      gazellacom_java_package_version: 'java-8'
      gazellacom_java_home: '/usr/lib64/jvm/jdk1.8.0_202'
      gazellacom_build_repo_url: git@bitbucket.org:Swissbytes/syscom.git 
      gazellacom_build_repo_branch: QA/COM-v2.13   #QA/COM-v2.13
      gazellacom_build_repo_filter: COM

      gazellacom_build_workspace: '/opt/workspace'
      gazellacom_build_workdir: "{{ gazellacom_build_workspace }}/{{  gazellacom_project }}/{{ gazellacom_project }}-deploy-{{ gazellacom_environment }}"
      gazellacom_build_sequence: "{{ gazellacom_build_workspace }}/{{  gazellacom_project }}/{{ gazellacom_project }}-sequence-{{ gazellacom_environment }}"
      gazellacom_build_sequence_file: "{{ gazellacom_build_sequence }}/sequence.ini"
      gazellacom_build_user: gazellacom_build
      gazellacom_build_group: "{{ gazellacom_build_user }}"
      gazellacom_remote_workdir: '/opt/deployments-awx'

- name: gomax integration deploy
  hosts: gazellacom
  become: true
  roles:
    - role: gazellacom-deploy
      gazellacom_mode: deploy
      gazellacom_project: laestrella # client
      gazellacom_environment: integration #integration, production
      gazellacom_remote_workdir: '/opt/deployment-awx'
