---
- name: gomax integration build
  hosts: localserver
#  become: true
  vars:
     gazellacom_number_build: "{{ lookup('file', gazellacom_build_sequence_file) }}"
  roles:
    - role: gazellacom-deploy
      gazellacom_mode: build
      gazellacom_project: gomax                         # client
      gazellacom_environment: integration               #integration, production
      gazellacom_build_profile_customer: gomax
      gazellacom_build_profile_environment: integration
      gazellacom_build_delete_workdir: true
      gazellacom_build_relative_path_to_deploy_dir: target/
      gazellacom_java_package_version: 'java-8'
      gazellacom_java_home: '/usr/lib64/jvm/jdk1.8.0_202'
      gazellacom_build_repo_url: git@bitbucket.org:Swissbytes/syscom.git 
      gazellacom_build_repo_branch: QA/COM-v2.13   #QA/COM-v2.13
      gazellacom_build_repo_filter: COM

- name: gomax integration deploy
  hosts: gazellacom
  become: true
  vars:
     gazellacom_number_build: "{{ lookup('file', gazellacom_build_sequence_file) }}"
  roles:
    - role: gazellacom-deploy
      gazellacom_mode: deploy
      gazellacom_project: gomax # client
      gazellacom_environment: integration #integration, production
      gazellacom_remote_workdir: '/opt/deployment-awx'
