---

- name: "Build app from {{ gazellacom_build_repo_url }} on '{{ gazellacom_builder_repo_branch }}'."
  block:

#    - name: fact with ignore error
#      ansible.builtin.set_fact:
#        gazellacom_number_build: "{{ lookup('file', gazellacom_build_sequence_file, errors='ignore') }}"
#      failed_when: false

    - name: "Ensure app sequences exists: {{ gazellacom_build_sequence }}"
      ansible.builtin.file:
        path: "{{ gazellacom_build_sequence }}"
        state: directory
        owner: "{{ gazellacom_build_user }}"
        group: "{{ gazellacom_build_group }}"
        mode: 0775
        force: yes

    - name: "Touch if dont exist {{ gazellacom_build_sequence_file }}"
      ansible.builtin.file:
        path: "{{ gazellacom_build_sequence_file }}"
        state: touch
        mode: u+rw,g-wx,o-rwx
        modification_time: preserve
        access_time: preserve

    - name: Print message if ansible version is greater than 2.7.0
      debug:
        msg: "Ansible version is  {{ ansible_version.full }}"

    - name: "Read file and put variable from {{ gazellacom_build_sequence_file }} "
      ansible.builtin.command: "cat {{ gazellacom_build_sequence_file }}"
      ignore_errors: true
      changed_when: false
      register: gazellacom_number_build_read
      become: yes

    - name: "Set global variable gazellacom_number_build"
      ansible.builtin.set_fact:
        gazellacom_number_build: "{{ gazellacom_number_build_read.stdout }}"

    - name: "Increment variable gazellacom_number_build = {{ gazellacom_number_build | int + 1 }}"
      ansible.builtin.set_fact: 
        gazellacom_number_build={{ gazellacom_number_build | int + 1 }}

    - name: "set sequence file {{ gazellacom_build_sequence_file }} to {{ gazellacom_number_build }}"
      ansible.builtin.shell: "echo {{ gazellacom_number_build }} > {{ gazellacom_build_sequence_file }}"

    - name: "Delete previous workdir {{ gazellacom_build_workdir }}."
      ansible.builtin.file:
        path: "{{ gazellacom_build_workdir }}"
        state: absent

    - name: "Ensure app workdir exists: {{ gazellacom_build_workdir }}"
      ansible.builtin.file:
        path: "{{ gazellacom_build_workdir }}"
        state: directory
        owner: "{{ gazellacom_build_user }}"
        group: "{{ gazellacom_build_group }}"
        mode: 0775
        force: yes

    - name: "Checkout the application source code Gazella COM"
#      become: yes
      ansible.builtin.git:
        repo: "{{ gazellacom_build_repo_url }}"
        dest: "{{ gazellacom_build_workdir }}"
        version: "{{ gazellacom_build_repo_branch }}"
      ignore_errors: yes  

    - name: "Bitbucket Recursively change ownership"
      become: yes
      file:
        path: "{{ gazellacom_build_workdir}}"
        state: directory
        recurse: yes
        owner: "{{ gazellacom_build_user }}"
        group: "{{ gazellacom_build_group }}"

    - name: "Git fix trusted directory"
      ansible.builtin.command: "git config --global --add safe.directory {{ gazellacom_build_workdir }}"
      args:
        chdir: "{{ gazellacom_build_workdir }}"

    - name: "Build the App using Maven"
      ansible.builtin.command: "mvn -X -s customer/{{ gazellacom_build_profile_customer }}/settings.xml clean package -Dbuild.number={{ gazellacom_number_build }} -P{{ gazellacom_build_profile_environment }}"
      register: mvn_build
      environment:
        JAVA_HOME: "{{ gazellacom_java_home }}"
      args:
        chdir: "{{ gazellacom_build_workdir }}"
      changed_when: false

    - name: "Display build application log"
      ansible.builtin.debug:
        var: mvn_build.stdout
#      when:
#        - display_mvn_output is defined
