---
- name: "Delete previous workdir (if requested)."
  ansible.builtin.file:
    path: /opt/demoansible2
    state: directory

- name: "Build app (if requested)."
  ansible.builtin.include_tasks: build.yml
#  when:
#    - gazellacom_build_app is defined and gazellacom_build_app
